In [14]:
import numpy as np
import pandas as pd
from math import exp

In [ ]:
def sigmoid_raw(x: np.array):
    return (1)/(1 + exp(-x))
sigmoid = np.vectorize(sigmoid_raw)



In [39]:
x = np.array([1.0, 2.0])
W = np.matrix([[1/2, 1/4], [0, -1/2], [1,-1]])
b = np.array([1, 0, 0])
print(b.shape)
h = (W@x) + b
print(h.shape)
sigmoid(h)

(3,)
(1, 3)


matrix([[0.88079708, 0.26894142, 0.26894142]])

[[ 2.]
 [-1.]
 [-1.]]
[[ 0.25   0.5    0.2  ]
 [ 0.    -0.5    0.125]
 [ 1.    -1.     0.25 ]]


In [ ]:
class Layer:
    def __init__(self,_in, _out, type:str = "lin"):
        def

In [ ]:
class MLP:
    def __init__(self, layers: list[int]):
        